name: Mulberry Partner Repo Scripts
on: 
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, closed]
  issue_comment:
    types: [created]
jobs:
  Build_And_Test_Partner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 1'

  Docker_Build_Partner:
    runs-on: ubuntu-latest
    needs: Build_And_Test_Partner
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'abracadabra'
      - run: exit 0
        if: steps.check.outputs.triggered == 'false' && github.event.pull_request.merged == false
      - uses: actions/checkout@v3
      - run: echo 'test 2. '
      
  Deploy_Partner:
    runs-on: ubuntu-latest
    needs: Docker_Build_Partner
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 3'

  Deploy_Partner_to_POC:
    runs-on: ubuntu-latest
    needs: Docker_Build_Partner
    if: contains(github.event.comment.body, 'abracadabra')
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 4'

  End_to_End_test:
    runs-on: ubuntu-latest
    needs: Build_And_Test_Partner
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 5'
      
  BDD_Scenarios:
    runs-on: ubuntu-latest
    needs: Build_And_Test_Partner
    if: github.ref == 'refs/heads/master'
    steps: 
      - uses: actions/checkout@v3
      - run: echo 'test 6'
