name: REPO Build and Tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  Build_And_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 1'
      - run: echo ${{ github.event.inputs.test_comment }}

  End_to_End_test:
    runs-on: ubuntu-latest
    needs: Build_And_Test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 5'
      
  BDD_Scenarios:
    runs-on: ubuntu-latest
    needs: Build_And_Test
    if: github.ref == 'refs/heads/master'
    steps: 
      - uses: actions/checkout@v3
      - run: echo 'test 6'
