name: Partner Workflow for Staging Test
on: 
  workflow_run:
    workflows: Partner Workflow for Merges
    types: completed
    branches: master
jobs:
  Staging_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '13.14.0'
      - uses: reedyuk/npm-version@1.1.1
        with:
          version: '7.20.6'
      - run: echo 'good'
