name: REPO Docker Build and Deploy for merges
on:
  push:
    branches:
      - master
      - develop
      - production
jobs:
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 2. '
      
  Deploy:
    runs-on: ubuntu-latest
    needs: Docker_Build
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 3'
