name: Workflow for Pull_request
on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  Build_And_Test_Partner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: $GITHUB_REF
      - run: echo 'test 1'
