name: Workflow for POC
on:
  workflow_dispatch:
    
jobs:
  Docker_Build_Partner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
  Deploy_Partner_to_POC:
    runs-on: ubuntu-latest
    needs: Docker_Build_Partner
    steps:
      - uses: actions/checkout@v3
