name: Workflow for Pull_request
on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  Build_And_Test_Partner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 1'
      
  End_to_End_test:
    runs-on: ubuntu-latest
    needs: Build_And_Test_Partner
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      
  BDD_Scenarios:
    runs-on: ubuntu-latest
    needs: Build_And_Test_Partner
    if: github.ref == 'refs/heads/master'
    steps: 
      - uses: actions/checkout@v3
