name: Partner Workflow for Merges
on:
  push:
    #branches:
      #- master
      #- develop
      #- production
jobs:
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 2. '
      - run: |
          if [[ $GITHUB_REF_NAME == 'master' ]]; then
            echo "ENV_NAME=staging" >> $GITHUB_ENV
          else
            echo "ENV_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi
      - run: printenv
      
  Deploy:
    runs-on: ubuntu-latest
    needs: Docker_Build
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test 3'
