name: Workflow for Pull_request
on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  Build_And_Test_Partner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - run: echo 'test 1'
